#!/usr/bin/env bash
# Negative control for the stability gate's exit status — REVIEW-005
# finding 1.
#
# The finding: ../002c-fix-loop-2/stability.sh printed DIFFERS and wrote an
# encoded exit-code line into its transcript when a gated artifact changed,
# but its own process still returned 0 — false-green. The fix makes the
# process exit 1 whenever any gated artifact differs. This script proves the
# fixed behaviour from both sides:
#
#   1. inject variance — append a marker line to one gated artifact and stage
#      it, so the index copy (the side of the comparison the regenerating
#      scripts never rewrite) no longer matches what regeneration produces;
#   2. run the gate and capture its real process exit status — must be 1;
#   3. restore the artifact and the index exactly as they were;
#   4. run the gate again — must be 0: green again, and the restore is shown
#      not to have left damage behind.
#
# The controlled artifact is typecheck.txt: capture.sh regenerates it from
# tsc's output, so the injected marker cannot leak into the regenerated bytes.
#
# The transcript keeps, for each run, the per-artifact status lines, the
# counts line, the encoded exit-code line, and the real process exit status.
# The gate's inline diff hunks are dropped: diff -u headers name mktemp paths
# and timestamps, which cannot be byte-stable.
#
# Prerequisites are the gate's own: npm ci done, git fetch origin done, port
# 8081 free, everything staged. This runs the full gate twice — expect ten
# minutes or more — and it temporarily modifies the index; both the working
# copy and the index of the controlled artifact are restored exactly before
# it exits.
#
# Run from the repo root.

set -u
OUT="docs/05-quality/evidence/002d-fix-loop-3/negative-control.txt"
GATE="docs/05-quality/evidence/002c-fix-loop-2/stability.sh"
TARGET="docs/05-quality/evidence/002b-fix-loop/typecheck.txt"
MARKER="NEGATIVE CONTROL: injected variance - not evidence, never committed"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# The restore below must be able to put back exactly what was there, so
# refuse to run unless the controlled artifact is clean against the index.
git show ":$TARGET" > "$TMP/index-copy" || exit 2
if ! cmp -s "$TARGET" "$TMP/index-copy"; then
  echo "$TARGET differs from its index copy — commit or restore it first" >&2
  exit 2
fi

run_gate() {
  bash "$GATE" > "$TMP/gate-out" 2>&1
  local code=$?
  echo "=== $1 ==="
  echo "\$ bash $GATE; echo \"process exit: \$?\""
  grep -E 'identical$|DIFFERS$|^gated artifacts:|^--- exit code' "$TMP/gate-out"
  echo "process exit: $code"
  echo
}

{
  echo "\$ bash docs/05-quality/evidence/002d-fix-loop-3/negative-control.sh"
  echo
  echo "gate under test:     $GATE"
  echo "controlled artifact: $TARGET"
  echo "injected line:       $MARKER"
  echo

  printf '%s\n' "$MARKER" >> "$TARGET"
  git add "$TARGET"
  run_gate "1. variance injected and staged — the gate must fail"

  cp "$TMP/index-copy" "$TARGET"
  git add "$TARGET"
  run_gate "2. restored — the gate must be green again"

  echo "The controlled artifact's working copy and index copy now hold the"
  echo "pre-injection bytes again; nothing else was touched. The injected line"
  echo "existed only in the working tree and the index, never in a commit."
} > "$OUT"
echo "wrote $OUT"
