#!/usr/bin/env bash
# The byte-stability gate that REVIEW-004 finding 1 failed.
#
# What it proves. Every artifact in the GATED list below is regenerated by its
# committed script and compared, byte for byte, against the copy in the Git
# index. At a committed head the index equals HEAD, so a reviewer who checks
# out the commit and runs this script is comparing the regenerated bytes
# against the committed bytes. Any difference is a failure: it is printed, and
# the script exits nonzero — the exit status is the gate's contract
# (REVIEW-005 finding 1; the first version printed the failure but returned 0).
#
# What it deliberately does not gate. The RUN-VARYING list is output that
# cannot be byte-stable without lying about what was measured: machine-local
# tool versions, and two commands whose answers come from the npm registry
# rather than from this repository. They are listed with the fields that vary
# and are not compared — comparing them would only record which machine and
# which day the reviewer ran on.
#
# The tree is left exactly as it was found: every artifact is restored from the
# index at the end, whether it matched or not, so running the gate never
# rewrites evidence.
#
# Prerequisites: `npm ci` done, `git fetch origin` done, port 8081 free, and
# every artifact below staged (it reads the index, not the working tree). Run
# from the repo root. Takes several minutes — it runs a full three-platform
# export and starts a dev server.

set -u
ROOT="docs/05-quality/evidence"
OUT="$ROOT/002c-fix-loop-2/stability.txt"
B="$ROOT/002b-fix-loop"
A="$ROOT/002a-app-skeleton"

GATED=(
  "$B/typecheck.txt"
  "$B/lint.txt"
  "$B/lint-file-list.txt"
  "$B/test.txt"
  "$B/prettier-check.txt"
  "$B/export-summary.txt"
  "$B/name-scan.txt"
  "$B/push-state.txt"
  "$B/app-json-diff.txt"
  "$A/git-ls-files.txt"
  "$ROOT/002c-fix-loop-2/dev-server.txt"
)

# file | the fields that vary
RUN_VARYING=(
  "environment.txt|node, npm and OS versions of the machine that ran it"
  "expo-doctor.txt|the expo-doctor build resolved from @latest, and its check count"
  "npm-audit.txt|the upstream npm advisory database"
  "expo-export.txt|the web bundle's content hash, and the order of the concurrent Web and SSR log lines"
)

SAVE=$(mktemp -d)
trap 'rm -rf "$SAVE"' EXIT

missing=0
for f in "${GATED[@]}"; do
  if ! git show ":$f" > "$SAVE/$(echo "$f" | tr / _)" 2>/dev/null; then
    echo "NOT STAGED: $f — stage it before running the gate" >&2
    missing=1
  fi
done
[ "$missing" -eq 0 ] || exit 2

bash "$B/capture.sh"      > /dev/null
bash "$B/name-scan.sh"    > /dev/null
bash "$B/fix-state.sh"    > /dev/null
bash "$B/tracked-files.sh" > /dev/null
bash "$ROOT/002c-fix-loop-2/dev-server.sh" > /dev/null

{
  echo "\$ bash docs/05-quality/evidence/002c-fix-loop-2/stability.sh"
  echo
  echo "=== gated: regenerated bytes vs the committed bytes ==="
  fails=0
  for f in "${GATED[@]}"; do
    if cmp -s "$f" "$SAVE/$(echo "$f" | tr / _)"; then
      printf '%-56s %s\n' "${f#$ROOT/}" "identical"
    else
      printf '%-56s %s\n' "${f#$ROOT/}" "DIFFERS"
      fails=$((fails + 1))
      echo "--- diff ---"
      diff -u "$SAVE/$(echo "$f" | tr / _)" "$f" | sed 's/^/    /'
      echo "--- end diff ---"
    fi
  done
  echo
  echo "gated artifacts: ${#GATED[@]}    differing: $fails"
  echo
  echo "=== run-varying: classified, not compared ==="
  for row in "${RUN_VARYING[@]}"; do
    printf '%-56s %s\n' "002b-fix-loop/${row%%|*}" "varies with: ${row#*|}"
  done
  echo
  echo "--- exit code: $([ "$fails" -eq 0 ] && echo 0 || echo 1) ---"
} > "$OUT"

# Leave the tree as found — this is a check, not a capture.
git checkout-index -f -- "${GATED[@]}" "$B/environment.txt" "$B/expo-doctor.txt" \
  "$B/npm-audit.txt" "$B/expo-export.txt"

cat "$OUT"

# The transcript above records the result; the process must return it too. A
# gate that prints DIFFERS and exits 0 is false-green (REVIEW-005 finding 1).
# Negative control: ../002d-fix-loop-3/negative-control.txt.
if [ "$fails" -eq 0 ]; then
  exit 0
else
  exit 1
fi
